Use gspaceenv:0
Signed-off-by: Lewis Krygger <lewis.krygger@gspace.com>

diff --git a/.github/workflows/linux-docker-coverage-swift.yml b/.github/workflows/linux-docker-coverage-swift.yml
--- a/.github/workflows/linux-docker-coverage-swift.yml
+++ b/.github/workflows/linux-docker-coverage-swift.yml
@@ -14,7 +14,7 @@ jobs:
   coverage:
     runs-on: [linux, gspace]
     container:
-      image: ghcr.io/gilmourspace/gspaceenv:main
+      image: ghcr.io/gilmourspace/gspaceenv:0
       credentials:
         username: ${{ secrets.WORKFLOW_USERNAME }}
         password: ${{ secrets.CONTAINER_PAT }}
@@ -28,4 +28,13 @@ jobs:
         - name: Coverage Test
           id: cov
           run: |
-            swift-test-codecov --minimum=${{ inputs.minimum-coverage }} --no-dependencies --no-tests -p table --exclude-path Tests .build/debug/codecov/*.json
+            OUTPUT=$(swift-test-codecov --minimum=${{ inputs.minimum-coverage }} --no-dependencies --no-tests -p table --exclude-path Tests .build/debug/codecov/*.json)
+            echo $OUTPUT >> $GITHUB_STEP_SUMMARY
+            if [ $? -eq 0 ]; then
+              COV=$(echo "$output" | grep ":" | head | cut -d":" -f2 | sed 's/^ //' | sed 's/%//g')
+              echo "**Coverage test passed: $COV**" >> $GITHUB_STEP_SUMMARY
+            else
+              COV=$(echo "$output" | grep ":" | head | cut -d":" -f2 | sed 's/^ //' | sed 's/%//g')
+              echo "**Coverage test failed: $COV**" >> $GITHUB_STEP_SUMMARY
+              exit 1
+            fi
