Added minimum-coverage input parameter and print out format the output so that the coverage test now prints out the table and reports the correct coverage value.

diff --git a/.github/workflows/macOS-native-coverage-swift.yml b/.github/workflows/macOS-native-coverage-swift.yml
--- a/.github/workflows/macOS-native-coverage-swift.yml
+++ b/.github/workflows/macOS-native-coverage-swift.yml
@@ -2,6 +2,12 @@ name: Swift Coverage Test
 
 on:
     workflow_call:
+        inputs:
+            minimum-coverage:
+                description: The minumum code coverage that the package should test.
+                required: false
+                type: number
+                default: 80
 
 defaults:
     run:
@@ -32,16 +38,19 @@ jobs:
         - name: Coverage Test
           id: cov
           run: |
-            cov=`swift-test-codecov -p table .build/debug/codecov/*.json | grep ":" | head | cut -d":" -f2 | sed 's/^ //'`
-            echo "{codecov}={$cov}" >> $GITHUB_OUTPUT
-            [[ cov -gte 80 ]]
+            output=`swift-test-codecov --minimum=${{ inputs.minimum-coverage }} --no-dependencies --no-tests -p table .build/debug/codecov/*.json || true`
+            echo "$output"
+            cov=`echo "$output" | grep ":" | head | cut -d":" -f2 | sed 's/^ //' | sed 's/%//g' || true`
+            echo "codecov=$cov" >> $GITHUB_OUTPUT
+            check=`printf "%.0f" "$cov"`
+            [[ "$check" -ge ${{ inputs.minimum-coverage }} ]]
 
         - name: Post Positive Result
           if: ${{ success() }}
           run: |
-            echo "::warning file=Package.swift,line=1,col=1::The current code coverage percentage is passing with ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.outputs.minimum_coverage }}%)."
+            echo "::warning file=Package.swift,line=1,col=1::The current code coverage percentage is passing with ${{ steps.cov.outputs.codecov }}% (minimum allowed: ${{ inputs.minimum-coverage }}%)."
 
         - name: Post Negative Result
           if: ${{ failure() }}
           run: |
-            echo "::error file=Package.swift,line=1,col=1::The current code coverage percentage is failing with ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.outputs.minimum_coverage }}%)."
+            echo "::error file=Package.swift,line=1,col=1::The current code coverage percentage is failing with ${{ steps.cov.outputs.codecov }}% (minimum allowed: ${{ inputs.minimum-coverage }}%)."
